variables: 
  DEPENDENCIES: 
    "build-essential 
    cmake 
    libboost1.63-dev
    liblemon-dev
    ophidian-units=2.3.1-1
    ophidian-DEF=5.8-2
    ophidian-LEF=5.8-1
    ophidian-Flute=1.0-1
    ophidian-verilog-parser=0.2.31"
  BUILD_LOCAL_DEPENDENCIES:
    "build-essential 
    cmake 
    libboost1.63-dev
    zlib1g-dev
    flex 
    libbison-dev"
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - deploy

build_ophidian_with_system_dependencies:
  image: ubuntu:artful
  stage: build
  before_script:
    - apt-get update -qq
    - apt-get install -y curl
    - curl -s https://packagecloud.io/install/repositories/tarberd/ophidian/script.deb.sh | bash
    - apt-get update -qq && apt-get install -y -qq $DEPENDENCIES
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ..
    - make -j2
    - cd test
    - ./ophidian_tests
  artifacts:
    paths:
      - build/

build_ophidian_with_system_dependencies_tests_fully_static:
  image: ubuntu:artful
  stage: build
  before_script:
    - apt-get update -qq
    - apt-get install -y curl
    - curl -s https://packagecloud.io/install/repositories/tarberd/ophidian/script.deb.sh | bash
    - apt-get update -qq && apt-get install -y $DEPENDENCIES
  script:
    - mkdir build && cd build
    - cmake -DOPHIDIAN_TESTS_FULLY_STATIC=ON
            -DCMAKE_INSTALL_PREFIX=/usr
            -DCMAKE_BUILD_TYPE=Release
            ..
    - make -j2
    - cd test
    - ./ophidian_tests
  artifacts:
    paths:
      - build/

build_ophidian_with_local_dependencies:
  image: ubuntu:artful
  stage: build
  before_script:
    - apt-get update -qq
    - apt-get install -y curl
    - curl -s https://packagecloud.io/install/repositories/tarberd/ophidian/script.deb.sh | bash
    - apt-get update -qq && apt-get install -y -qq $BUILD_LOCAL_DEPENDENCIES
  script:
    - sh build_dependencies.sh
    - mkdir build && cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ..
    - make -j2
    - cd test
    - ./ophidian_tests
  artifacts:
    paths:
      - build/
