variables: 
  DEPENDENCIES: 
    "build-essential 
    git
    cmake 
    libboost1.63-dev
    liblemon-dev
    ophidian-units
    ophidian-def
    ophidian-lef
    ophidian-flute
    ophidian-verilog-parser"
  BUILD_LOCAL_DEPENDENCIES:
    "build-essential 
    git
    cmake 
    libboost1.63-dev
    zlib1g-dev
    flex 
    libbison-dev"
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

build_ophidian_with_system_packages:
  image: ubuntu:artful
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y curl
    - curl -s https://packagecloud.io/install/repositories/tarberd/ophidian/script.deb.sh | bash
    - apt-get update && apt-get install -y $DEPENDENCIES
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr 
            -DCMAKE_BUILD_TYPE=Release 
            ..
    - make -j2
    - cd test
    - ./ophidian_tests
  artifacts:
    paths:
      - build/

build_ophidian_with_system_packages_static_libc:
  image: ubuntu:artful
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y curl
    - curl -s https://packagecloud.io/install/repositories/tarberd/ophidian/script.deb.sh | bash
    - apt-get update && apt-get install -y $DEPENDENCIES
  script:
    - mkdir build && cd build
    - cmake -DOPHIDIAN_TESTS_FULLY_STATIC=ON
            -DCMAKE_INSTALL_PREFIX=/usr
            -DCMAKE_BUILD_TYPE=Release
            ..
    - make -j2
    - cd test
    - ./ophidian_tests
  artifacts:
    paths:
      - build/

build_ophidian_with_install_script_source:
  image: ubuntu:artful
  stage: build
  before_script:
    - apt-get update && apt-get install -y $BUILD_LOCAL_DEPENDENCIES
  script:
    - echo "y" | bash build_dependencies.sh
    - mkdir build && cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr 
            -DCMAKE_BUILD_TYPE=Release
            ..
    - make -j2
    - cd test
    - ./ophidian_tests
  artifacts:
    paths:
      - build/

build_ophidian_with_install_script_system:
  image: ubuntu:artful
  stage: build
  before_script:
    - apt-get update && apt-get install -y $BUILD_LOCAL_DEPENDENCIES
  script:
    - echo y | bash build_dependencies.sh --install_to /usr/local
    - mkdir build && cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr 
            -DCMAKE_BUILD_TYPE=Release
            ..
    - make -j2
    - cd test
    - ./ophidian_tests
  artifacts:
    paths:
      - build/
